server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/ecom/users/**
          filters:
           - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/ecom/auth/**
          
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/ecom/orders/**
          filters:
           - AuthenticationFilter

        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/ecom/order-lines/**
          filters:
           - AuthenticationFilter

        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/ecom/products/**
          filters:
           - AuthenticationFilter

        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/ecom/payments/**
          filters:
           - AuthenticationFilter
